# MACOS
# =============================================================================

brew:
  # git
  - git git-lfs gh
  # shell
  - zsh fzf bat eza btop oh-my-posh
  - neovim lazygit ripgrep fd
  # python
  - python python-freethreading uv
  # pwsh
  - powershell --cask
  # fonts
  - font-computer-modern
  - font-jetbrains-mono-nerd-font

# LINUX
# =============================================================================

apt:
  # snap package manager
  - snapd --fix-missing
  # git
  - git-lfs --fix-missing
  # shell
  - unzip # oh-my-posh dependency
  - script: curl -s https://ohmyposh.dev/install.sh | bash -s
  # fonts
  - fonts-jetbrains-mono
  - fonts-lmodern

snap:
  # git
  - gh
  # pwsh
  - powershell --classic

# windows
# =============================================================================

winget:
  # git
  - git.git github.gitLFS github.cli
  # shell
  - microsoft.powershell JanDeDobbeleer.OhMyPosh
  - neovim.neovim JesseDuffield.lazygit
  # python
  - python.python.3.14 astral-sh.uv # REVIEW: python version & free-threading
  # chezmoi
  - twpayne.chezmoi
  # fonts
  - devcom.JetBrainsMonoNerdFont

scoop:
  # nvim
  - gcc # nvim dependency
  # shell
  - btop-lhm
